Fix error on Node 16 if ABI dir doesn't exist
Apparently in Node 16, `fs.rmdirSync()` requires an existence check as
it will no longer succeed when the directory doesn't exist.

When running `hardhat compile`, error was:

  An unexpected error occurred:
  Error: ENOENT: no such file or directory, stat './abi'